### ISSUE TITLE
Icon support for SettingButton

### ISSUE THREAD

**Issue by joekw** [aheze/Setting#12]
I want to include a bunch of links at the bottom of my setting page and it would be nice if i could add an icon for these items to match the rest of them ☺️

<img width="488" alt="Screenshot 2023-02-28 at 08 38 45" src="https://user-images.githubusercontent.com/1735113/221799461-eae6670b-344b-4eb8-962c-596500098677.png">

**Comment by aheze** [comment]
Added in [1.0.1](https://github.com/aheze/Setting/releases/tag/1.0.1)
