### ISSUE TITLE
compile error in SettingGroup file, line 91

### ISSUE THREAD

**Issue by codinggooner** [aheze/Setting#20]
The error information is : Initializer for conditional binding must have Optional type, not 'Color'

backgroundColor is not optional type

**Comment by transat** [comment]
I'm getting this too @codinggooner. Why did you close the issue? Have I missed something obvious?

**Comment by miaoruiyuan** [comment]
the same problem..

**Comment by aheze** [comment]
I might have messed up, give me a bit

**Comment by transat** [comment]
@aheze The error I'm getting is `Initializer for conditional binding must have
Optional type, not 'Color'`

I've quashed it by removing the if let here:
```
if let backgroundColor {
    backgroundColor
}
```
Otherwise I think you should be able to change that var in Setting.swift to: `public static var backgroundColor: Color?` ?

**Comment by vince-hz** [comment]
Same compile error with XCode 14.3. Sad.

**Comment by aheze** [comment]
The problem is fixed in the latest commit. I need to make a new release though for Swift Package Manager, hang tight
