### ISSUE TITLE
Theme entire setting stack

### ISSUE THREAD

**Issue by joekw** [aheze/Setting#7]
Would be nice to set the background colour of certain items throughout the SettingStack, rather than having to set each and every SettingPage and SettingGroup

**Comment by aheze** [comment]
Hmm, like a universal theme? I'll think about how to add it.

Also maybe allowing custom `SettingItem` subclass structs would be helpful.

**Comment by aheze** [comment]
Basic support added in [1.0.1](https://github.com/aheze/Setting/releases/tag/1.0.1).

```swift
SettingStack {
    /* ... */
}
.environment(\.settingPrimaryColor, .blue) /// text
.environment(\.settingSecondaryColor, .blue) /// indicators
.environment(\.settingAccentColor, .blue) /// currently not used
.environment(\.settingBackgroundColor, .blue) /// background color of entire page
.environment(\.settingSecondaryBackgroundColor, .blue) /// background color of elements like `SettingGroup`
```

**Comment by aheze** [comment]
Expanded support depends on https://github.com/aheze/Setting/issues/23
