### ISSUE TITLE
Set foreground colour of .image SettingIconView

### ISSUE THREAD

**Issue by joekw** [aheze/Setting#8]
I'm using custom SF symbols and they're tinted black in light mode. would be good to be able to set the foregroundColor of the .image on SettingIconView

<img width="657" alt="Screenshot 2023-02-24 at 11 23 52" src="https://user-images.githubusercontent.com/1735113/221167460-ece76e40-86eb-47f3-84d8-663222c60e51.png">

**Comment by aheze** [comment]
Will add support, thanks for the suggestion.

**Comment by aheze** [comment]
Supported in [1.0.1](https://github.com/aheze/Setting/releases/tag/1.0.1)
