### ISSUE TITLE
TextFields as SettingTextField

### ISSUE THREAD

**Issue by juliusschmid** [aheze/Setting#9]
I really appreciate your work. It looks very nice native. But what would be even better would be if you could add text fields not only via a custom view, but that they would be like for example SettingButton SettingTextField. Thanks a lot!

**Comment by aheze** [comment]
Gotcha, will add in the next release.

**Comment by juliusschmid** [comment]
Thanks a lot!

**Comment by aheze** [comment]
Added in ff195cb, will bundle it into a release in a bit.

<img width="409" alt="Enter text here" src="https://user-images.githubusercontent.com/49819455/221269236-9bc88465-b2a1-45ba-9c38-2ae24ec9aaa7.png">

**Comment by aheze** [comment]
Added in [1.0.1](https://github.com/aheze/Setting/releases/tag/1.0.1)! Sorry for the delay
